"use client";

import {motion, useAnimation} from "motion/react";
import {useEffect} from "react";

interface EducationPointProps {
    size?: number;
    school?: string;
    year?: string;
    major?: string;
    description?: string;
}

export default function EducationPoint({size = 160, school, year, major, description}: EducationPointProps) {
    const controls = useAnimation();

    useEffect(() => {
        const randomY = Math.random() * 20 - 10;
        const randomX = Math.random() * 10 - 5;
        const randomDuration = 6 + Math.random() * 3;

        controls.start({
            y: [0, randomY, 0],
            x: [0, randomX, 0, -randomX, 0],
            transition: {repeat: Infinity, duration: randomDuration, ease: "easeInOut"},
        });
    }, [controls]);

    return (
        <div className="flex flex-row gap-4 sm:gap-15 w-full">
            <motion.div
                id="education-point"
                className="shrink-0 mx-auto sm:mx-0"
                animate={controls}
            >
                <svg
                    width={size}
                    height={size}
                    viewBox="0 0 160 160"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <g clipPath="url(#clip0_194_3221)">
                        <rect
                            x="50"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="60"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="70"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="80"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="90"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="100"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="30"
                            y="10"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="40"
                            y="10"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="50"
                            y="10"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="10"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="10"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="10"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="10"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="10"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="10"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="120"
                            y="10"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="20"
                            y="20"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="30"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="20"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="20"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="30"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="20"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="30"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="30"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="40"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="20"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="40"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="40"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            y="50"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="20"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="50"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="150"
                            y="50"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            y="60"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="20"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="60"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="150"
                            y="60"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            y="70"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="20"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="70"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="80"
                            y="70"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="90"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="70"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="150"
                            y="70"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            y="80"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="20"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="80"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="80"
                            y="80"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="90"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="80"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="150"
                            y="80"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            y="90"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="20"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="90"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="150"
                            y="90"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            y="100"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="20"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="100"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="150"
                            y="100"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="110"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="20"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="110"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="110"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="10"
                            y="120"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="20"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="30"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="120"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="140"
                            y="120"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="20"
                            y="130"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="30"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="40"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="50"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="120"
                            y="130"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="130"
                            y="130"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="30"
                            y="140"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="40"
                            y="140"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="50"
                            y="140"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="60"
                            y="140"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="70"
                            y="140"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="80"
                            y="140"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="90"
                            y="140"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="100"
                            y="140"
                            width="10"
                            height="10"
                            fill="#F00035"
                        />
                        <rect
                            x="110"
                            y="140"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="120"
                            y="140"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="50"
                            y="150"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="60"
                            y="150"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="70"
                            y="150"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="80"
                            y="150"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="90"
                            y="150"
                            width="10"
                            height="10"
                            fill="black"
                        />
                        <rect
                            x="100"
                            y="150"
                            width="10"
                            height="10"
                            fill="black"
                        />
                    </g>
                    <defs>
                        <clipPath id="clip0_194_3221">
                            <rect
                                width="160"
                                height="160"
                                fill="white"
                            />
                        </clipPath>
                    </defs>
                </svg>
            </motion.div>
            <div className="flex flex-col text-center sm:text-left m-auto border-b-3 pb-3 border-crimson">
                {school && <h3 className="font-bold text-lg">{school}</h3>}
                {year && <span className="text-sm text-gray-500">{year}</span>}
                {major && <span className="font-medium">{major}</span>}
                {description && <p className="text-sm text-gray-600 mt-1">{description}</p>}
            </div>
        </div>
    );
}
