interface ProgressPointProps {
    size?: number;
}

export default function ProgressPoint({size = 160}: ProgressPointProps) {
    const height = (size / 160) * 689;
    return (
        <svg
            className="relative bottom-8"
            width={size}
            height={height}
            viewBox="0 0 160 689"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <rect
                x="60"
                y="70"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="70"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="70"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="70"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="80"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="80"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="80"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="80"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="90"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="90"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="90"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="90"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="100"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="100"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="100"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="100"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="110"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="110"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="110"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="110"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="120"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="120"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="120"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="120"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="130"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="130"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="130"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="130"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="140"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="140"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="140"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="140"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="150"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="150"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="150"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="150"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="160"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="160"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="160"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="160"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="170"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="170"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="170"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="170"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="180"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="180"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="180"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="180"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="190"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="190"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="190"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="190"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="200"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="200"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="200"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="200"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="210"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="210"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="210"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="210"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="220"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="220"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="220"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="220"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="230"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="230"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="230"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="230"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="240"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="240"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="240"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="240"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="250"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="250"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="250"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="250"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="260"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="260"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="260"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="260"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="270"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="270"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="270"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="270"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="280"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="280"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="280"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="280"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="290"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="290"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="290"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="290"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="300"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="300"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="300"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="300"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="310"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="310"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="310"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="310"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="320"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="320"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="320"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="320"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="330"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="330"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="330"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="330"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="340"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="340"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="340"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="340"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="350"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="350"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="350"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="350"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="360"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="360"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="360"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="360"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="370"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="370"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="370"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="370"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="380"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="380"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="380"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="380"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="390"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="390"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="390"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="390"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="400"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="400"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="400"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="400"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="410"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="410"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="410"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="410"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="420"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="420"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="420"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="420"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="430"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="430"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="430"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="430"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="440"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="440"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="440"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="440"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="450"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="450"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="450"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="450"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="460"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="460"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="460"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="460"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="470"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="470"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="470"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="470"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="480"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="480"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="480"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="480"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="490"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="490"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="490"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="490"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="500"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="500"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="500"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="500"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="510"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="510"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="510"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="510"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="520"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="520"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="520"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="520"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="530"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="530"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="530"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="530"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="540"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="540"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="540"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="540"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="170"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="170"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="170"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="170"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="180"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="180"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="180"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="180"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="190"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="190"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="190"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="190"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="200"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="200"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="200"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="200"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="210"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="210"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="210"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="210"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="220"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="220"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="220"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="220"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="230"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="230"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="230"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="230"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="240"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="240"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="240"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="240"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="250"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="250"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="250"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="250"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="260"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="260"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="260"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="260"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="270"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="270"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="270"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="270"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="280"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="280"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="280"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="280"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="290"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="290"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="290"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="290"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="300"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="300"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="300"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="300"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="310"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="310"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="310"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="310"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="320"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="320"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="320"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="320"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="330"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="330"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="330"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="330"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="340"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="340"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="340"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="340"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="350"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="350"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="350"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="350"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="360"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="360"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="360"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="360"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="370"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="370"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="370"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="370"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="380"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="380"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="380"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="380"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="390"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="390"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="390"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="390"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="400"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="400"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="400"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="400"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="410"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="410"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="410"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="410"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="420"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="420"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="420"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="420"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="430"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="430"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="430"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="430"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="440"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="440"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="440"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="440"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="450"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="450"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="450"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="450"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="460"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="460"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="460"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="460"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="470"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="470"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="470"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="470"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="480"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="480"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="480"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="480"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="490"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="490"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="490"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="490"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="500"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="500"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="500"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="500"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="510"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="510"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="510"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="510"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="520"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="520"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="520"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="520"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="530"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="530"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="530"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="530"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="540"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="540"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="540"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="540"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="550"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="550"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="550"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="550"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="560"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="560"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="560"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="560"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="570"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="570"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="570"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="570"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="580"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="580"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="580"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="580"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="590"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="590"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="590"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="590"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="600"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="600"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="600"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="600"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="610"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="610"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="610"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="610"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="620"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="620"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="620"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="620"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="630"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="630"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="630"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="630"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="640"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="640"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="640"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="640"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="140"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="150"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="10"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="10"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="20"
                y="10"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="130"
                y="10"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="140"
                y="10"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="150"
                y="10"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="20"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="20"
                y="20"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="30"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="40"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="110"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="120"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="130"
                y="20"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="140"
                y="20"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="150"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="20"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="30"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="40"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="50"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="90"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="100"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="110"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="120"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="130"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="140"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="150"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="20"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="30"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="40"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="50"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="60"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="70"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="80"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="90"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="100"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="110"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="120"
                y="40"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="130"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="30"
                y="50"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="40"
                y="50"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="50"
                y="50"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="60"
                y="50"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="70"
                y="50"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="50"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="50"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="100"
                y="50"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="110"
                y="50"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="120"
                y="50"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="50"
                y="60"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="60"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="60"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="60"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="60"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="100"
                y="60"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="609"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="609"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="140"
                y="609"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="150"
                y="609"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="619"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="619"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="20"
                y="619"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="130"
                y="619"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="140"
                y="619"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="150"
                y="619"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="629"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="629"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="20"
                y="629"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="30"
                y="629"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="40"
                y="629"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="110"
                y="629"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="120"
                y="629"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="130"
                y="629"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="140"
                y="629"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="150"
                y="629"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="20"
                y="639"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="30"
                y="639"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="40"
                y="639"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="50"
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="90"
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="100"
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="110"
                y="639"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="120"
                y="639"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="130"
                y="639"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="140"
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="150"
                y="639"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="20"
                y="649"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="30"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="40"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="50"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="60"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="70"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="100"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="110"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="120"
                y="649"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="130"
                y="649"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="30"
                y="659"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="40"
                y="659"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="50"
                y="659"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="60"
                y="659"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="70"
                y="659"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="659"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="659"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="100"
                y="659"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="110"
                y="659"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="120"
                y="659"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="50"
                y="669"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="669"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="669"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="669"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="669"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="100"
                y="669"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="679"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="80"
                y="679"
                width="10"
                height="10"
                fill="black"
            />
        </svg>
    );
}
