"use client";

interface StopPointProps {
    size?: number;
}

export default function StopPoint({size = 160}: StopPointProps) {
    const height = (size / 160) * 50;
    return (
        <svg
            className="relative bottom-12"
            width={size}
            height={height}
            viewBox="0 0 160 50"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <rect
                x="60"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="10"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="10"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="10"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="10"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="20"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="30"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="40"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="50"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="20"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="20"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="100"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="110"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="120"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="130"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="140"
                y="20"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="20"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="30"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="40"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="50"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="60"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="70"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="80"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="90"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="100"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="110"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="120"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="130"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="140"
                y="30"
                width="10"
                height="10"
                fill="#F00035"
            />
            <rect
                x="150"
                y="30"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="10"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="20"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="30"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="40"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="50"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="60"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="70"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="80"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="90"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="100"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="110"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="120"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="130"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="140"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
            <rect
                x="150"
                y="40"
                width="10"
                height="10"
                fill="black"
            />
        </svg>
    );
}
